name: Florian Dierickx
author: Florian Dierickx
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-feed
  
url: http://floriandierickx.github.io

navigation:
- root: Home
  url: /
- root: CV
  url: /cv
- root: Blog
  url: /blog
  first-level:
    - text: Tags
      url: /blog/tags/index.html
- root: Publications
  url: /publications
- root: Library
  url: /library
  first-level:
    - text: Belgian Climate Policy
      url: /library/belgium/index.html
    - text: Belgian Energy Policy
      url: /library/belgium-e/index.html
    - text: 100 % Renewables
      url: /library/renewables/index.html
    - text: Integrated Assessment Models
      url: /library/iam/index.html
    - text: EU ETS & Carbon Leakage List
      url: /library/eu-ets/index.html
    - text: Copernicus Climate Change
      url: /library/copernicus/index.html
- root: Agenda
  url: /agenda
- root: Twitter Threads
  url: /twitter
  icon: /icons/twitter.jpg
  first-level:
    - text: 04/05/19 - EU Water Stress [FR/BE case & Copernicus ECMWF forecast]
      url: /twitter/water/index.html
    - text: 27/02/19 - Quantitative Easing for the Climate
      url: /twitter/qe-climate/index.html
    - text: 19/02/19 - Bruegel Debate on Decarbonization Policies
      url: /twitter/bruegel/index.html
    - text: 18/02/19 - [Dys]functioning EU ETS (English)
      url: /twitter/eu-ets-en/index.html
    - text: 31/01/19 - [Dys]functioning EU ETS (Dutch)
      url: /twitter/eu-ets/index.html
    - text: 27/11/18 - Programmation pluriannuelle de l’énergie Jancovici [FR]
      url: /twitter/jancovici/index.html
    - text: 27/11/18 - CMCC & ETH Low-Carbon Finance Webinar
      url: /twitter/cmcc/index.html
- root: EIB Climate & Energy
  url: /eib-consultation
  icon: icon-you-want-1
  first-level:
    - text: EIB Documentation
      url: /eib-consultation/eib/index.html
     # second-level:
     #   - text: Second Level
     #     url: second-level-link.html
    - text: Climate Change & Finance
      url: /eib-consultation/cc-cb/index.html