name: Florian Dierickx
author: Florian Dierickx
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-feed
  
url: http://floriandierickx.github.io

title_image: "https://floriandierickx.github.io/icons/banner.jpeg"

navigation:
- root: Home
  url: /
- root: CV
  url: /cv
- root: Blog
  url: /blog
  first-level:
    - text: Tags
      url: /blog/tags/index.html
- root: Publications
  url: /publications
- root: Library
  url: /library
  first-level:
    - text: Belgian Climate Policy
      url: /library/belgium/index.html
    - text: Belgian Energy Policy
      url: /library/belgium-e/index.html
    - text: 100 % Renewables
      url: /library/renewables/index.html
    - text: Integrated Assessment Models
      url: /library/iam/index.html
    - text: EU ETS & Carbon Leakage List
      url: /library/eu-ets/index.html
    - text: Copernicus Climate Change
      url: /library/copernicus/index.html
    - text: Climate Change & Finance
      url: /library/cc-cb/index.html
    - text: EIB Climate & Energy Review
      url: /library/eib/index.html
- root: Agenda
  url: /agenda
- root: Emission Budget[beta]
  url: /emission-budget